// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the tokens for attributes stored in flash


// Identifier tags for tokens
// Creator for attribute: check-in interval, endpoint: 1
#define CREATOR_CHECK_IN_INTERVAL_1 0xB000
#define NVM3KEY_CHECK_IN_INTERVAL_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB000 )
// Creator for attribute: long poll interval, endpoint: 1
#define CREATOR_LONG_POLL_INTERVAL_1 0xB001
#define NVM3KEY_LONG_POLL_INTERVAL_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB001 )
// Creator for attribute: short poll interval, endpoint: 1
#define CREATOR_SHORT_POLL_INTERVAL_1 0xB002
#define NVM3KEY_SHORT_POLL_INTERVAL_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB002 )
// Creator for attribute: fast poll timeout, endpoint: 1
#define CREATOR_FAST_POLL_TIMEOUT_1 0xB003
#define NVM3KEY_FAST_POLL_TIMEOUT_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB003 )
// Creator for attribute: Boot_Count, endpoint: 1
#define CREATOR_BOOT_COUNT_1 0xB004
#define NVM3KEY_BOOT_COUNT_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB004 )
// Creator for attribute: RS485_Device_Id1, endpoint: 1
#define CREATOR_RS485_Device_Id1_1 0xB005
#define NVM3KEY_RS485_Device_Id1_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB005 )
// Creator for attribute: RS485_Device_Id2, endpoint: 1
#define CREATOR_RS485_Device_Id2_1 0xB006
#define NVM3KEY_RS485_Device_Id2_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB006 )
// Creator for attribute: RS485_Device_Id3, endpoint: 1
#define CREATOR_RS485_Device_Id3_1 0xB007
#define NVM3KEY_RS485_Device_Id3_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB007 )
// Creator for attribute: RS485_Device_Id4, endpoint: 1
#define CREATOR_RS485_Device_Id4_1 0xB008
#define NVM3KEY_RS485_Device_Id4_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB008 )
// Creator for attribute: RS485_Device_Id5, endpoint: 1
#define CREATOR_RS485_Device_Id5_1 0xB009
#define NVM3KEY_RS485_Device_Id5_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB009 )
// Creator for attribute: RS485_Device_Id6, endpoint: 1
#define CREATOR_RS485_Device_Id6_1 0xB00A
#define NVM3KEY_RS485_Device_Id6_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00A )
// Creator for attribute: RS485_Device_Id7, endpoint: 1
#define CREATOR_RS485_Device_Id7_1 0xB00B
#define NVM3KEY_RS485_Device_Id7_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00B )
// Creator for attribute: RS485_Device_Id8, endpoint: 1
#define CREATOR_RS485_Device_Id8_1 0xB00C
#define NVM3KEY_RS485_Device_Id8_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00C )
// Creator for attribute: Button_ActionTypeId, endpoint: 1
#define CREATOR_Button_ActionTypeId_1 0xB00D
#define NVM3KEY_Button_ActionTypeId_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00D )


// Types for the tokens
#ifdef DEFINETYPES
typedef uint8_t  tokType_on_off;
typedef uint8_t  tokType_current_level;
typedef uint16_t  tokType_start_up_color_temperature_mireds;
typedef uint32_t  tokType_check_in_interval;
typedef uint32_t  tokType_long_poll_interval;
typedef uint16_t  tokType_short_poll_interval;
typedef uint16_t  tokType_fast_poll_timeout;
typedef uint32_t  tokType_boot_count;
typedef uint32_t  tokType_boot_count;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_rs485_device_id1;
typedef uint8_t  tokType_rs485_device_id2;
typedef uint8_t  tokType_rs485_device_id3;
typedef uint8_t  tokType_rs485_device_id4;
typedef uint8_t  tokType_rs485_device_id5;
typedef uint8_t  tokType_rs485_device_id6;
typedef uint8_t  tokType_rs485_device_id7;
typedef uint8_t  tokType_rs485_device_id8;
typedef uint8_t  tokType_button_actiontypeid;
typedef uint8_t  tokType_button_actiontypeid;
typedef uint8_t  tokType_rs485_device_id8;
typedef uint8_t  tokType_rs485_device_id7;
typedef uint8_t  tokType_rs485_device_id6;
typedef uint8_t  tokType_rs485_device_id5;
typedef uint8_t  tokType_rs485_device_id4;
typedef uint8_t  tokType_rs485_device_id3;
typedef uint8_t  tokType_rs485_device_id2;
typedef uint8_t  tokType_rs485_device_id1;
typedef uint32_t  tokType_boot_count;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_rs485_device_id1;
typedef uint8_t  tokType_rs485_device_id2;
typedef uint8_t  tokType_rs485_device_id3;
typedef uint8_t  tokType_rs485_device_id4;
typedef uint8_t  tokType_rs485_device_id5;
typedef uint8_t  tokType_rs485_device_id6;
typedef uint8_t  tokType_rs485_device_id7;
typedef uint8_t  tokType_rs485_device_id8;
typedef uint8_t  tokType_button_actiontypeid;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_rs485_device_id1;
typedef uint8_t  tokType_rs485_device_id2;
typedef uint8_t  tokType_rs485_device_id3;
typedef uint8_t  tokType_rs485_device_id4;
typedef uint8_t  tokType_rs485_device_id5;
typedef uint8_t  tokType_rs485_device_id6;
typedef uint8_t  tokType_rs485_device_id7;
typedef uint8_t  tokType_rs485_device_id8;
typedef uint8_t  tokType_button_actiontypeid;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_rs485_device_id1;
typedef uint8_t  tokType_rs485_device_id2;
typedef uint8_t  tokType_rs485_device_id3;
typedef uint8_t  tokType_rs485_device_id4;
typedef uint8_t  tokType_rs485_device_id5;
typedef uint8_t  tokType_rs485_device_id6;
typedef uint8_t  tokType_rs485_device_id7;
typedef uint8_t  tokType_rs485_device_id8;
typedef uint8_t  tokType_button_actiontypeid;
typedef uint8_t  tokType_button_actiontypeid;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_rs485_device_id1;
typedef uint8_t  tokType_rs485_device_id2;
typedef uint8_t  tokType_rs485_device_id3;
typedef uint8_t  tokType_rs485_device_id4;
typedef uint8_t  tokType_rs485_device_id5;
typedef uint8_t  tokType_rs485_device_id6;
typedef uint8_t  tokType_rs485_device_id7;
typedef uint8_t  tokType_rs485_device_id8;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_rs485_device_id1;
typedef uint8_t  tokType_rs485_device_id2;
typedef uint8_t  tokType_rs485_device_id3;
typedef uint8_t  tokType_rs485_device_id4;
typedef uint8_t  tokType_rs485_device_id5;
typedef uint8_t  tokType_rs485_device_id6;
typedef uint8_t  tokType_rs485_device_id7;
typedef uint8_t  tokType_rs485_device_id8;
typedef uint8_t  tokType_button_actiontypeid;
#endif // DEFINETYPES


// Actual token definitions
#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(CHECK_IN_INTERVAL_1, tokType_check_in_interval, 0x00003840)
DEFINE_BASIC_TOKEN(LONG_POLL_INTERVAL_1, tokType_long_poll_interval, 0x00000014)
DEFINE_BASIC_TOKEN(SHORT_POLL_INTERVAL_1, tokType_short_poll_interval, 0x0002)
DEFINE_BASIC_TOKEN(FAST_POLL_TIMEOUT_1, tokType_fast_poll_timeout, 0x0028)
DEFINE_BASIC_TOKEN(BOOT_COUNT_1, tokType_boot_count, 0)
DEFINE_BASIC_TOKEN(RS485_Device_Id1_1, tokType_rs485_device_id1, 0)
DEFINE_BASIC_TOKEN(RS485_Device_Id2_1, tokType_rs485_device_id2, 0)
DEFINE_BASIC_TOKEN(RS485_Device_Id3_1, tokType_rs485_device_id3, 0)
DEFINE_BASIC_TOKEN(RS485_Device_Id4_1, tokType_rs485_device_id4, 0)
DEFINE_BASIC_TOKEN(RS485_Device_Id5_1, tokType_rs485_device_id5, 0)
DEFINE_BASIC_TOKEN(RS485_Device_Id6_1, tokType_rs485_device_id6, 0)
DEFINE_BASIC_TOKEN(RS485_Device_Id7_1, tokType_rs485_device_id7, 0)
DEFINE_BASIC_TOKEN(RS485_Device_Id8_1, tokType_rs485_device_id8, 0)
DEFINE_BASIC_TOKEN(Button_ActionTypeId_1, tokType_button_actiontypeid, 0)
#endif // DEFINETOKENS


// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint) do {\
  uint8_t ptr[4]; \
  uint8_t curNetwork = emberGetCurrentNetwork(); \
  uint8_t epNetwork; \
  epNetwork = emberAfNetworkIndexFromEndpoint(1); \
  if((endpoint) == 1 || ((endpoint) == EMBER_BROADCAST_ENDPOINT && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_check_in_interval *)ptr, TOKEN_CHECK_IN_INTERVAL_1); \
    emberAfWriteServerAttribute(1, ZCL_POLL_CONTROL_CLUSTER_ID, ZCL_CHECK_IN_INTERVAL_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT32U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_long_poll_interval *)ptr, TOKEN_LONG_POLL_INTERVAL_1); \
    emberAfWriteServerAttribute(1, ZCL_POLL_CONTROL_CLUSTER_ID, ZCL_LONG_POLL_INTERVAL_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT32U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_short_poll_interval *)ptr, TOKEN_SHORT_POLL_INTERVAL_1); \
    emberAfWriteServerAttribute(1, ZCL_POLL_CONTROL_CLUSTER_ID, ZCL_SHORT_POLL_INTERVAL_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT16U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_fast_poll_timeout *)ptr, TOKEN_FAST_POLL_TIMEOUT_1); \
    emberAfWriteServerAttribute(1, ZCL_POLL_CONTROL_CLUSTER_ID, ZCL_FAST_POLL_TIMEOUT_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT16U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_boot_count *)ptr, TOKEN_BOOT_COUNT_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_BOOT_COUNT_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT32U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_rs485_device_id1 *)ptr, TOKEN_RS485_Device_Id1_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_RS485_Device_Id1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_rs485_device_id2 *)ptr, TOKEN_RS485_Device_Id2_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_RS485_Device_Id2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_rs485_device_id3 *)ptr, TOKEN_RS485_Device_Id3_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_RS485_Device_Id3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_rs485_device_id4 *)ptr, TOKEN_RS485_Device_Id4_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_RS485_Device_Id4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_rs485_device_id5 *)ptr, TOKEN_RS485_Device_Id5_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_RS485_Device_Id5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_rs485_device_id6 *)ptr, TOKEN_RS485_Device_Id6_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_RS485_Device_Id6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_rs485_device_id7 *)ptr, TOKEN_RS485_Device_Id7_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_RS485_Device_Id7_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_rs485_device_id8 *)ptr, TOKEN_RS485_Device_Id8_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_RS485_Device_Id8_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_button_actiontypeid *)ptr, TOKEN_Button_ActionTypeId_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_Button_ActionTypeId_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
  } \
} while(false)


// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER do {\
  uint8_t allZeroData[4]; \
  MEMSET(allZeroData, 0, 4); \
  if ( data == NULL ) data = allZeroData; \
  if ( endpoint == 1 ) { \
    if ( clusterId == 0x20 ) { \
      if ( metadata->attributeId == 0x0000 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_CHECK_IN_INTERVAL_1, data); \
      if ( metadata->attributeId == 0x0001 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_LONG_POLL_INTERVAL_1, data); \
      if ( metadata->attributeId == 0x0002 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_SHORT_POLL_INTERVAL_1, data); \
      if ( metadata->attributeId == 0x0003 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_FAST_POLL_TIMEOUT_1, data); \
    } else if ( clusterId == 0xFD01 ) { \
      if ( metadata->attributeId == 0x000D && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_BOOT_COUNT_1, data); \
      if ( metadata->attributeId == 0x0016 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_RS485_Device_Id1_1, data); \
      if ( metadata->attributeId == 0x0017 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_RS485_Device_Id2_1, data); \
      if ( metadata->attributeId == 0x0018 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_RS485_Device_Id3_1, data); \
      if ( metadata->attributeId == 0x0019 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_RS485_Device_Id4_1, data); \
      if ( metadata->attributeId == 0x001A && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_RS485_Device_Id5_1, data); \
      if ( metadata->attributeId == 0x001B && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_RS485_Device_Id6_1, data); \
      if ( metadata->attributeId == 0x001C && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_RS485_Device_Id7_1, data); \
      if ( metadata->attributeId == 0x001D && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_RS485_Device_Id8_1, data); \
      if ( metadata->attributeId == 0x001E && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_Button_ActionTypeId_1, data); \
    } \
  } \
} while(false)


