// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the tokens for attributes stored in flash


// Identifier tags for tokens
// Creator for attribute: current level, endpoint: 1
#define CREATOR_CURRENT_LEVEL_1 0xB000
#define NVM3KEY_CURRENT_LEVEL_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB000 )
// Creator for attribute: Boot_Count, endpoint: 1
#define CREATOR_BOOT_COUNT_1 0xB002
#define NVM3KEY_BOOT_COUNT_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB002 )
// Creator for attribute: 6_Bt_Id1, endpoint: 1
#define CREATOR_6_Bt_Id1_1 0xB003
#define NVM3KEY_6_Bt_Id1_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB003 )
// Creator for attribute: 6_Bt_Id2, endpoint: 1
#define CREATOR_6_Bt_Id2_1 0xB004
#define NVM3KEY_6_Bt_Id2_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB004 )
// Creator for attribute: 6_Bt_Id3, endpoint: 1
#define CREATOR_6_Bt_Id3_1 0xB005
#define NVM3KEY_6_Bt_Id3_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB005 )
// Creator for attribute: 6_Bt_Id4, endpoint: 1
#define CREATOR_6_Bt_Id4_1 0xB006
#define NVM3KEY_6_Bt_Id4_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB006 )
// Creator for attribute: 6_Bt_Id5, endpoint: 1
#define CREATOR_6_Bt_Id5_1 0xB007
#define NVM3KEY_6_Bt_Id5_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB007 )
// Creator for attribute: 6_Bt_Id6, endpoint: 1
#define CREATOR_6_Bt_Id6_1 0xB008
#define NVM3KEY_6_Bt_Id6_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB008 )
// Creator for attribute: 6_Bt_Zone1, endpoint: 1
#define CREATOR_6_Bt_Zone1_1 0xB009
#define NVM3KEY_6_Bt_Zone1_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB009 )
// Creator for attribute: 6_Bt_Zone2, endpoint: 1
#define CREATOR_6_Bt_Zone2_1 0xB00A
#define NVM3KEY_6_Bt_Zone2_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00A )
// Creator for attribute: 6_Bt_Zone3, endpoint: 1
#define CREATOR_6_Bt_Zone3_1 0xB00B
#define NVM3KEY_6_Bt_Zone3_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00B )
// Creator for attribute: 6_Bt_Zone4, endpoint: 1
#define CREATOR_6_Bt_Zone4_1 0xB00C
#define NVM3KEY_6_Bt_Zone4_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00C )
// Creator for attribute: 6_Bt_Zone5, endpoint: 1
#define CREATOR_6_Bt_Zone5_1 0xB00D
#define NVM3KEY_6_Bt_Zone5_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00D )
// Creator for attribute: 6_Bt_Zone6, endpoint: 1
#define CREATOR_6_Bt_Zone6_1 0xB00E
#define NVM3KEY_6_Bt_Zone6_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00E )
// Creator for attribute: 6_Bt_Scene1, endpoint: 1
#define CREATOR_6_Bt_Scene1_1 0xB00F
#define NVM3KEY_6_Bt_Scene1_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00F )
// Creator for attribute: 6_Bt_Scene2, endpoint: 1
#define CREATOR_6_Bt_Scene2_1 0xB010
#define NVM3KEY_6_Bt_Scene2_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB010 )
// Creator for attribute: 6_Bt_Scene3, endpoint: 1
#define CREATOR_6_Bt_Scene3_1 0xB011
#define NVM3KEY_6_Bt_Scene3_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB011 )
// Creator for attribute: 6_Bt_Scene4, endpoint: 1
#define CREATOR_6_Bt_Scene4_1 0xB012
#define NVM3KEY_6_Bt_Scene4_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB012 )
// Creator for attribute: 6_Bt_Scene5, endpoint: 1
#define CREATOR_6_Bt_Scene5_1 0xB013
#define NVM3KEY_6_Bt_Scene5_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB013 )
// Creator for attribute: 6_Bt_Scene6, endpoint: 1
#define CREATOR_6_Bt_Scene6_1 0xB014
#define NVM3KEY_6_Bt_Scene6_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB014 )
// Creator for attribute: current level, endpoint: 196
#define CREATOR_CURRENT_LEVEL_196 0xB015
#define NVM3KEY_CURRENT_LEVEL_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB015 )
// Creator for attribute: Boot_Count, endpoint: 196
#define CREATOR_BOOT_COUNT_196 0xB017
#define NVM3KEY_BOOT_COUNT_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB017 )
// Creator for attribute: 6_Bt_Id1, endpoint: 196
#define CREATOR_6_Bt_Id1_196 0xB018
#define NVM3KEY_6_Bt_Id1_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB018 )
// Creator for attribute: 6_Bt_Id2, endpoint: 196
#define CREATOR_6_Bt_Id2_196 0xB019
#define NVM3KEY_6_Bt_Id2_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB019 )
// Creator for attribute: 6_Bt_Id3, endpoint: 196
#define CREATOR_6_Bt_Id3_196 0xB01A
#define NVM3KEY_6_Bt_Id3_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01A )
// Creator for attribute: 6_Bt_Id4, endpoint: 196
#define CREATOR_6_Bt_Id4_196 0xB01B
#define NVM3KEY_6_Bt_Id4_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01B )
// Creator for attribute: 6_Bt_Id5, endpoint: 196
#define CREATOR_6_Bt_Id5_196 0xB01C
#define NVM3KEY_6_Bt_Id5_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01C )
// Creator for attribute: 6_Bt_Id6, endpoint: 196
#define CREATOR_6_Bt_Id6_196 0xB01D
#define NVM3KEY_6_Bt_Id6_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01D )
// Creator for attribute: 6_Bt_Zone1, endpoint: 196
#define CREATOR_6_Bt_Zone1_196 0xB01E
#define NVM3KEY_6_Bt_Zone1_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01E )
// Creator for attribute: 6_Bt_Zone2, endpoint: 196
#define CREATOR_6_Bt_Zone2_196 0xB01F
#define NVM3KEY_6_Bt_Zone2_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01F )
// Creator for attribute: 6_Bt_Zone3, endpoint: 196
#define CREATOR_6_Bt_Zone3_196 0xB020
#define NVM3KEY_6_Bt_Zone3_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB020 )
// Creator for attribute: 6_Bt_Zone4, endpoint: 196
#define CREATOR_6_Bt_Zone4_196 0xB021
#define NVM3KEY_6_Bt_Zone4_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB021 )
// Creator for attribute: 6_Bt_Zone5, endpoint: 196
#define CREATOR_6_Bt_Zone5_196 0xB022
#define NVM3KEY_6_Bt_Zone5_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB022 )
// Creator for attribute: 6_Bt_Zone6, endpoint: 196
#define CREATOR_6_Bt_Zone6_196 0xB023
#define NVM3KEY_6_Bt_Zone6_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB023 )
// Creator for attribute: 6_Bt_Scene1, endpoint: 196
#define CREATOR_6_Bt_Scene1_196 0xB024
#define NVM3KEY_6_Bt_Scene1_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB024 )
// Creator for attribute: 6_Bt_Scene2, endpoint: 196
#define CREATOR_6_Bt_Scene2_196 0xB025
#define NVM3KEY_6_Bt_Scene2_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB025 )
// Creator for attribute: 6_Bt_Scene3, endpoint: 196
#define CREATOR_6_Bt_Scene3_196 0xB026
#define NVM3KEY_6_Bt_Scene3_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB026 )
// Creator for attribute: 6_Bt_Scene4, endpoint: 196
#define CREATOR_6_Bt_Scene4_196 0xB027
#define NVM3KEY_6_Bt_Scene4_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB027 )
// Creator for attribute: 6_Bt_Scene5, endpoint: 196
#define CREATOR_6_Bt_Scene5_196 0xB028
#define NVM3KEY_6_Bt_Scene5_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB028 )
// Creator for attribute: 6_Bt_Scene6, endpoint: 196
#define CREATOR_6_Bt_Scene6_196 0xB029
#define NVM3KEY_6_Bt_Scene6_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB029 )


// Types for the tokens
#ifdef DEFINETYPES
typedef uint8_t  tokType_on_off;
typedef uint8_t  tokType_current_level;
typedef uint16_t  tokType_start_up_color_temperature_mireds;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_6_bt_id1;
typedef uint8_t  tokType_6_bt_id2;
typedef uint8_t  tokType_6_bt_id3;
typedef uint8_t  tokType_6_bt_id5;
typedef uint8_t  tokType_6_bt_id4;
typedef uint8_t  tokType_6_bt_id6;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_6_bt_id1;
typedef uint8_t  tokType_6_bt_id2;
typedef uint8_t  tokType_6_bt_id3;
typedef uint8_t  tokType_6_bt_id6;
typedef uint8_t  tokType_6_bt_id5;
typedef uint8_t  tokType_6_bt_id4;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_6_bt_id1;
typedef uint8_t  tokType_6_bt_id2;
typedef uint8_t  tokType_6_bt_id4;
typedef uint8_t  tokType_6_bt_id3;
typedef uint8_t  tokType_6_bt_id5;
typedef uint8_t  tokType_6_bt_id6;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_6_bt_id1;
typedef uint8_t  tokType_6_bt_id3;
typedef uint8_t  tokType_6_bt_id2;
typedef uint8_t  tokType_6_bt_id4;
typedef uint8_t  tokType_6_bt_id5;
typedef uint8_t  tokType_6_bt_id6;
typedef uint8_t  tokType_6_bt_id6;
typedef uint8_t  tokType_6_bt_id5;
typedef uint8_t  tokType_6_bt_id4;
typedef uint8_t  tokType_6_bt_id3;
typedef uint8_t  tokType_6_bt_id2;
typedef uint8_t  tokType_6_bt_id1;
typedef uint32_t  tokType_boot_count;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_6_bt_id1;
typedef uint8_t  tokType_6_bt_id2;
typedef uint8_t  tokType_6_bt_id3;
typedef uint8_t  tokType_6_bt_id4;
typedef uint8_t  tokType_6_bt_id5;
typedef uint8_t  tokType_6_bt_id6;
typedef uint8_t  tokType_6_bt_zone4;
typedef uint8_t  tokType_6_bt_zone5;
typedef uint8_t  tokType_6_bt_zone6;
typedef uint8_t  tokType_6_bt_scene1;
typedef uint8_t  tokType_6_bt_zone1;
typedef uint8_t  tokType_6_bt_zone2;
typedef uint8_t  tokType_6_bt_zone3;
typedef uint8_t  tokType_6_bt_scene2;
typedef uint8_t  tokType_6_bt_scene3;
typedef uint8_t  tokType_6_bt_scene4;
typedef uint8_t  tokType_6_bt_scene5;
typedef uint8_t  tokType_6_bt_scene6;
#endif // DEFINETYPES


// Actual token definitions
#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(CURRENT_LEVEL_1, tokType_current_level, 0x00)
DEFINE_BASIC_TOKEN(BOOT_COUNT_1, tokType_boot_count, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id1_1, tokType_6_bt_id1, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id2_1, tokType_6_bt_id2, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id3_1, tokType_6_bt_id3, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id4_1, tokType_6_bt_id4, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id5_1, tokType_6_bt_id5, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id6_1, tokType_6_bt_id6, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone1_1, tokType_6_bt_zone1, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone2_1, tokType_6_bt_zone2, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone3_1, tokType_6_bt_zone3, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone4_1, tokType_6_bt_zone4, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone5_1, tokType_6_bt_zone5, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone6_1, tokType_6_bt_zone6, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene1_1, tokType_6_bt_scene1, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene2_1, tokType_6_bt_scene2, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene3_1, tokType_6_bt_scene3, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene4_1, tokType_6_bt_scene4, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene5_1, tokType_6_bt_scene5, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene6_1, tokType_6_bt_scene6, 0)
DEFINE_BASIC_TOKEN(CURRENT_LEVEL_196, tokType_current_level, 0x00)
DEFINE_BASIC_TOKEN(BOOT_COUNT_196, tokType_boot_count, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id1_196, tokType_6_bt_id1, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id2_196, tokType_6_bt_id2, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id3_196, tokType_6_bt_id3, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id4_196, tokType_6_bt_id4, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id5_196, tokType_6_bt_id5, 0)
DEFINE_BASIC_TOKEN(6_Bt_Id6_196, tokType_6_bt_id6, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone1_196, tokType_6_bt_zone1, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone2_196, tokType_6_bt_zone2, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone3_196, tokType_6_bt_zone3, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone4_196, tokType_6_bt_zone4, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone5_196, tokType_6_bt_zone5, 0)
DEFINE_BASIC_TOKEN(6_Bt_Zone6_196, tokType_6_bt_zone6, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene1_196, tokType_6_bt_scene1, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene2_196, tokType_6_bt_scene2, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene3_196, tokType_6_bt_scene3, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene4_196, tokType_6_bt_scene4, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene5_196, tokType_6_bt_scene5, 0)
DEFINE_BASIC_TOKEN(6_Bt_Scene6_196, tokType_6_bt_scene6, 0)
#endif // DEFINETOKENS


// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint) do {\
  uint8_t ptr[4]; \
  uint8_t curNetwork = emberGetCurrentNetwork(); \
  uint8_t epNetwork; \
  epNetwork = emberAfNetworkIndexFromEndpoint(1); \
  if((endpoint) == 1 || ((endpoint) == EMBER_BROADCAST_ENDPOINT && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_current_level *)ptr, TOKEN_CURRENT_LEVEL_1); \
    emberAfWriteServerAttribute(1, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_CURRENT_LEVEL_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_boot_count *)ptr, TOKEN_BOOT_COUNT_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_BOOT_COUNT_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT32U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id1 *)ptr, TOKEN_6_Bt_Id1_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id2 *)ptr, TOKEN_6_Bt_Id2_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id3 *)ptr, TOKEN_6_Bt_Id3_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id4 *)ptr, TOKEN_6_Bt_Id4_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id5 *)ptr, TOKEN_6_Bt_Id5_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id6 *)ptr, TOKEN_6_Bt_Id6_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone1 *)ptr, TOKEN_6_Bt_Zone1_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone2 *)ptr, TOKEN_6_Bt_Zone2_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone3 *)ptr, TOKEN_6_Bt_Zone3_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone4 *)ptr, TOKEN_6_Bt_Zone4_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone5 *)ptr, TOKEN_6_Bt_Zone5_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone6 *)ptr, TOKEN_6_Bt_Zone6_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene1 *)ptr, TOKEN_6_Bt_Scene1_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene2 *)ptr, TOKEN_6_Bt_Scene2_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene3 *)ptr, TOKEN_6_Bt_Scene3_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene4 *)ptr, TOKEN_6_Bt_Scene4_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene5 *)ptr, TOKEN_6_Bt_Scene5_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene6 *)ptr, TOKEN_6_Bt_Scene6_1); \
    emberAfWriteManufacturerSpecificServerAttribute(1, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
  } \
  epNetwork = emberAfNetworkIndexFromEndpoint(196); \
  if((endpoint) == 196 || ((endpoint) == EMBER_BROADCAST_ENDPOINT && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_current_level *)ptr, TOKEN_CURRENT_LEVEL_196); \
    emberAfWriteServerAttribute(196, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_CURRENT_LEVEL_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_boot_count *)ptr, TOKEN_BOOT_COUNT_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_BOOT_COUNT_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT32U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id1 *)ptr, TOKEN_6_Bt_Id1_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id2 *)ptr, TOKEN_6_Bt_Id2_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id3 *)ptr, TOKEN_6_Bt_Id3_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id4 *)ptr, TOKEN_6_Bt_Id4_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id5 *)ptr, TOKEN_6_Bt_Id5_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_id6 *)ptr, TOKEN_6_Bt_Id6_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Id6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone1 *)ptr, TOKEN_6_Bt_Zone1_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone2 *)ptr, TOKEN_6_Bt_Zone2_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone3 *)ptr, TOKEN_6_Bt_Zone3_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone4 *)ptr, TOKEN_6_Bt_Zone4_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone5 *)ptr, TOKEN_6_Bt_Zone5_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_zone6 *)ptr, TOKEN_6_Bt_Zone6_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Zone6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene1 *)ptr, TOKEN_6_Bt_Scene1_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene2 *)ptr, TOKEN_6_Bt_Scene2_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene3 *)ptr, TOKEN_6_Bt_Scene3_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene4 *)ptr, TOKEN_6_Bt_Scene4_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene5 *)ptr, TOKEN_6_Bt_Scene5_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_6_bt_scene6 *)ptr, TOKEN_6_Bt_Scene6_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_6_Bt_Scene6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
  } \
} while(false)


// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER do {\
  uint8_t allZeroData[4]; \
  MEMSET(allZeroData, 0, 4); \
  if ( data == NULL ) data = allZeroData; \
  if ( endpoint == 1 ) { \
    if ( clusterId == 0x08 ) { \
      if ( metadata->attributeId == 0x0000 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_CURRENT_LEVEL_1, data); \
    } else if ( clusterId == 0xFD01 ) { \
      if ( metadata->attributeId == 0x000D && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_BOOT_COUNT_1, data); \
      if ( metadata->attributeId == 0x0016 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id1_1, data); \
      if ( metadata->attributeId == 0x0017 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id2_1, data); \
      if ( metadata->attributeId == 0x0018 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id3_1, data); \
      if ( metadata->attributeId == 0x0019 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id4_1, data); \
      if ( metadata->attributeId == 0x001A && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id5_1, data); \
      if ( metadata->attributeId == 0x001B && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id6_1, data); \
      if ( metadata->attributeId == 0x001E && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone1_1, data); \
      if ( metadata->attributeId == 0x001F && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone2_1, data); \
      if ( metadata->attributeId == 0x0020 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone3_1, data); \
      if ( metadata->attributeId == 0x0021 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone4_1, data); \
      if ( metadata->attributeId == 0x0022 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone5_1, data); \
      if ( metadata->attributeId == 0x0023 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone6_1, data); \
      if ( metadata->attributeId == 0x0026 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene1_1, data); \
      if ( metadata->attributeId == 0x0027 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene2_1, data); \
      if ( metadata->attributeId == 0x0028 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene3_1, data); \
      if ( metadata->attributeId == 0x0029 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene4_1, data); \
      if ( metadata->attributeId == 0x002A && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene5_1, data); \
      if ( metadata->attributeId == 0x002B && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene6_1, data); \
    } \
  } else if ( endpoint == 196) { \
    if ( clusterId == 0x08 ) { \
      if ( metadata->attributeId == 0x0000 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_CURRENT_LEVEL_196, data); \
    } else if ( clusterId == 0xFD01 ) { \
      if ( metadata->attributeId == 0x000D && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_BOOT_COUNT_196, data); \
      if ( metadata->attributeId == 0x0016 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id1_196, data); \
      if ( metadata->attributeId == 0x0017 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id2_196, data); \
      if ( metadata->attributeId == 0x0018 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id3_196, data); \
      if ( metadata->attributeId == 0x0019 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id4_196, data); \
      if ( metadata->attributeId == 0x001A && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id5_196, data); \
      if ( metadata->attributeId == 0x001B && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Id6_196, data); \
      if ( metadata->attributeId == 0x001E && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone1_196, data); \
      if ( metadata->attributeId == 0x001F && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone2_196, data); \
      if ( metadata->attributeId == 0x0020 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone3_196, data); \
      if ( metadata->attributeId == 0x0021 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone4_196, data); \
      if ( metadata->attributeId == 0x0022 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone5_196, data); \
      if ( metadata->attributeId == 0x0023 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Zone6_196, data); \
      if ( metadata->attributeId == 0x0026 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene1_196, data); \
      if ( metadata->attributeId == 0x0027 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene2_196, data); \
      if ( metadata->attributeId == 0x0028 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene3_196, data); \
      if ( metadata->attributeId == 0x0029 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene4_196, data); \
      if ( metadata->attributeId == 0x002A && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene5_196, data); \
      if ( metadata->attributeId == 0x002B && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_6_Bt_Scene6_196, data); \
    } \
  } \
} while(false)


