// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the tokens for attributes stored in flash


// Identifier tags for tokens
// Creator for attribute: on/off, endpoint: 1
#define CREATOR_ON_OFF_1 0xB000
#define NVM3KEY_ON_OFF_1 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB000 )
// Creator for attribute: on/off, endpoint: 2
#define CREATOR_ON_OFF_2 0xB002
#define NVM3KEY_ON_OFF_2 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB002 )
// Creator for attribute: on/off, endpoint: 3
#define CREATOR_ON_OFF_3 0xB004
#define NVM3KEY_ON_OFF_3 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB004 )
// Creator for attribute: Boot_Count, endpoint: 196
#define CREATOR_BOOT_COUNT_196 0xB006
#define NVM3KEY_BOOT_COUNT_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB006 )
// Creator for attribute: C4_LED_1, endpoint: 196
#define CREATOR_C4_LED_1_196 0xB007
#define NVM3KEY_C4_LED_1_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB007 )
// Creator for attribute: C4_LED_2, endpoint: 196
#define CREATOR_C4_LED_2_196 0xB008
#define NVM3KEY_C4_LED_2_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB008 )
// Creator for attribute: C4_LED_3, endpoint: 196
#define CREATOR_C4_LED_3_196 0xB009
#define NVM3KEY_C4_LED_3_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB009 )
// Creator for attribute: C4_LED_4, endpoint: 196
#define CREATOR_C4_LED_4_196 0xB00A
#define NVM3KEY_C4_LED_4_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00A )
// Creator for attribute: C4_LED_5, endpoint: 196
#define CREATOR_C4_LED_5_196 0xB00B
#define NVM3KEY_C4_LED_5_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00B )
// Creator for attribute: C4_LED_6, endpoint: 196
#define CREATOR_C4_LED_6_196 0xB00C
#define NVM3KEY_C4_LED_6_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00C )
// Creator for attribute: C4_LED_7, endpoint: 196
#define CREATOR_C4_LED_7_196 0xB00D
#define NVM3KEY_C4_LED_7_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00D )
// Creator for attribute: C4_LED_8, endpoint: 196
#define CREATOR_C4_LED_8_196 0xB00E
#define NVM3KEY_C4_LED_8_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00E )
// Creator for attribute: C4_BUTTON_1, endpoint: 196
#define CREATOR_C4_BUTTON_1_196 0xB00F
#define NVM3KEY_C4_BUTTON_1_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB00F )
// Creator for attribute: C4_BUTTON_2, endpoint: 196
#define CREATOR_C4_BUTTON_2_196 0xB010
#define NVM3KEY_C4_BUTTON_2_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB010 )
// Creator for attribute: C4_BUTTON_3, endpoint: 196
#define CREATOR_C4_BUTTON_3_196 0xB011
#define NVM3KEY_C4_BUTTON_3_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB011 )
// Creator for attribute: C4_BUTTON_4, endpoint: 196
#define CREATOR_C4_BUTTON_4_196 0xB012
#define NVM3KEY_C4_BUTTON_4_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB012 )
// Creator for attribute: C4_BUTTON_5, endpoint: 196
#define CREATOR_C4_BUTTON_5_196 0xB013
#define NVM3KEY_C4_BUTTON_5_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB013 )
// Creator for attribute: C4_BUTTON_6, endpoint: 196
#define CREATOR_C4_BUTTON_6_196 0xB014
#define NVM3KEY_C4_BUTTON_6_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB014 )
// Creator for attribute: C4_BUTTON_7, endpoint: 196
#define CREATOR_C4_BUTTON_7_196 0xB015
#define NVM3KEY_C4_BUTTON_7_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB015 )
// Creator for attribute: C4_BUTTON_8, endpoint: 196
#define CREATOR_C4_BUTTON_8_196 0xB016
#define NVM3KEY_C4_BUTTON_8_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB016 )
// Creator for attribute: C4_LED_1_STATE, endpoint: 196
#define CREATOR_C4_LED_1_STATE_196 0xB017
#define NVM3KEY_C4_LED_1_STATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB017 )
// Creator for attribute: C4_LED_2_STATE, endpoint: 196
#define CREATOR_C4_LED_2_STATE_196 0xB018
#define NVM3KEY_C4_LED_2_STATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB018 )
// Creator for attribute: C4_LED_3_STATE, endpoint: 196
#define CREATOR_C4_LED_3_STATE_196 0xB019
#define NVM3KEY_C4_LED_3_STATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB019 )
// Creator for attribute: C4_LED_4_STATE, endpoint: 196
#define CREATOR_C4_LED_4_STATE_196 0xB01A
#define NVM3KEY_C4_LED_4_STATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01A )
// Creator for attribute: C4_LED_5_STATE, endpoint: 196
#define CREATOR_C4_LED_5_STATE_196 0xB01B
#define NVM3KEY_C4_LED_5_STATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01B )
// Creator for attribute: C4_LED_6_STATE, endpoint: 196
#define CREATOR_C4_LED_6_STATE_196 0xB01C
#define NVM3KEY_C4_LED_6_STATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01C )
// Creator for attribute: C4_LED_7_STATE, endpoint: 196
#define CREATOR_C4_LED_7_STATE_196 0xB01D
#define NVM3KEY_C4_LED_7_STATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01D )
// Creator for attribute: C4_LED_8_STATE, endpoint: 196
#define CREATOR_C4_LED_8_STATE_196 0xB01E
#define NVM3KEY_C4_LED_8_STATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01E )
// Creator for attribute: C4_LED_DIM_UP_RATE, endpoint: 196
#define CREATOR_C4_LED_DIM_UP_RATE_196 0xB01F
#define NVM3KEY_C4_LED_DIM_UP_RATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB01F )
// Creator for attribute: C4_LED_DIM_DOWN_RATE, endpoint: 196
#define CREATOR_C4_LED_DIM_DOWN_RATE_196 0xB020
#define NVM3KEY_C4_LED_DIM_DOWN_RATE_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB020 )
// Creator for attribute: C4_LED_DIM_MIN, endpoint: 196
#define CREATOR_C4_LED_DIM_MIN_196 0xB021
#define NVM3KEY_C4_LED_DIM_MIN_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB021 )
// Creator for attribute: C4_LED_DIM_MAX, endpoint: 196
#define CREATOR_C4_LED_DIM_MAX_196 0xB022
#define NVM3KEY_C4_LED_DIM_MAX_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB022 )
// Creator for attribute: C4_LED_ON_TIME, endpoint: 196
#define CREATOR_C4_LED_ON_TIME_196 0xB023
#define NVM3KEY_C4_LED_ON_TIME_196 ( NVM3KEY_DOMAIN_ZIGBEE | 0xB023 )


// Types for the tokens
#ifdef DEFINETYPES
typedef uint8_t  tokType_on_off;
typedef uint8_t  tokType_current_level;
typedef uint16_t  tokType_start_up_color_temperature_mireds;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_c4_led_1;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_4;
typedef uint8_t  tokType_c4_led_6;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_c4_led_1;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_6;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_4;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_c4_led_1;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_4;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_6;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_c4_led_1;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_4;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_6;
typedef uint8_t  tokType_c4_led_6;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_4;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_1;
typedef uint32_t  tokType_boot_count;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_c4_led_1;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_4;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_6;
typedef uint8_t  tokType_c4_led_7;
typedef uint8_t  tokType_c4_led_8;
typedef uint8_t  tokType_c4_button_4;
typedef uint8_t  tokType_c4_button_5;
typedef uint8_t  tokType_c4_button_6;
typedef uint8_t  tokType_c4_button_7;
typedef uint8_t  tokType_c4_button_8;
typedef uint8_t  tokType_c4_led_1_state;
typedef uint8_t  tokType_c4_led_2_state;
typedef uint8_t  tokType_c4_led_3_state;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_c4_led_1;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_4;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_6;
typedef uint8_t  tokType_c4_led_7;
typedef uint8_t  tokType_c4_led_8;
typedef uint8_t  tokType_c4_button_4;
typedef uint8_t  tokType_c4_button_5;
typedef uint8_t  tokType_c4_button_6;
typedef uint8_t  tokType_c4_button_7;
typedef uint8_t  tokType_c4_button_8;
typedef uint8_t  tokType_c4_led_1_state;
typedef uint8_t  tokType_c4_led_2_state;
typedef uint8_t  tokType_c4_led_3_state;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_c4_led_1;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_4;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_6;
typedef uint8_t  tokType_c4_led_7;
typedef uint8_t  tokType_c4_led_8;
typedef uint8_t  tokType_c4_button_4;
typedef uint8_t  tokType_c4_button_5;
typedef uint8_t  tokType_c4_button_6;
typedef uint8_t  tokType_c4_button_7;
typedef uint8_t  tokType_c4_button_8;
typedef uint8_t  tokType_c4_led_1_state;
typedef uint8_t  tokType_c4_led_2_state;
typedef uint8_t  tokType_c4_led_3_state;
typedef uint8_t  tokType_c4_led_4_state;
typedef uint8_t  tokType_c4_led_5_state;
typedef uint8_t  tokType_c4_led_6_state;
typedef uint8_t  tokType_c4_led_7_state;
typedef uint8_t  tokType_c4_led_8_state;
typedef uint32_t  tokType_boot_count;
typedef uint8_t  tokType_c4_led_1;
typedef uint8_t  tokType_c4_led_2;
typedef uint8_t  tokType_c4_led_3;
typedef uint8_t  tokType_c4_led_4;
typedef uint8_t  tokType_c4_led_5;
typedef uint8_t  tokType_c4_led_6;
typedef uint8_t  tokType_c4_led_7;
typedef uint8_t  tokType_c4_led_8;
typedef uint8_t  tokType_c4_button_4;
typedef uint8_t  tokType_c4_button_5;
typedef uint8_t  tokType_c4_button_6;
typedef uint8_t  tokType_c4_button_7;
typedef uint8_t  tokType_c4_button_8;
typedef uint8_t  tokType_c4_led_1_state;
typedef uint8_t  tokType_c4_led_2_state;
typedef uint8_t  tokType_c4_led_3_state;
typedef uint8_t  tokType_c4_led_4_state;
typedef uint8_t  tokType_c4_led_5_state;
typedef uint8_t  tokType_c4_led_6_state;
typedef uint8_t  tokType_c4_led_7_state;
typedef uint8_t  tokType_c4_led_8_state;
typedef uint8_t  tokType_c4_led_on_time;
typedef uint8_t  tokType_c4_led_dim_max;
typedef uint8_t  tokType_c4_led_dim_min;
typedef uint8_t  tokType_c4_led_dim_down_rate;
typedef uint8_t  tokType_c4_led_dim_up_rate;
typedef uint8_t  tokType_c4_button_1;
typedef uint8_t  tokType_c4_button_2;
typedef uint8_t  tokType_c4_button_3;
#endif // DEFINETYPES


// Actual token definitions
#ifdef DEFINETOKENS
DEFINE_BASIC_TOKEN(ON_OFF_1, tokType_on_off, 0x00)
DEFINE_BASIC_TOKEN(ON_OFF_2, tokType_on_off, 0x00)
DEFINE_BASIC_TOKEN(ON_OFF_3, tokType_on_off, 0x00)
DEFINE_BASIC_TOKEN(BOOT_COUNT_196, tokType_boot_count, 0)
DEFINE_BASIC_TOKEN(C4_LED_1_196, tokType_c4_led_1, 0)
DEFINE_BASIC_TOKEN(C4_LED_2_196, tokType_c4_led_2, 0)
DEFINE_BASIC_TOKEN(C4_LED_3_196, tokType_c4_led_3, 0)
DEFINE_BASIC_TOKEN(C4_LED_4_196, tokType_c4_led_4, 0)
DEFINE_BASIC_TOKEN(C4_LED_5_196, tokType_c4_led_5, 0)
DEFINE_BASIC_TOKEN(C4_LED_6_196, tokType_c4_led_6, 0)
DEFINE_BASIC_TOKEN(C4_LED_7_196, tokType_c4_led_7, 0)
DEFINE_BASIC_TOKEN(C4_LED_8_196, tokType_c4_led_8, 0)
DEFINE_BASIC_TOKEN(C4_BUTTON_1_196, tokType_c4_button_1, 0)
DEFINE_BASIC_TOKEN(C4_BUTTON_2_196, tokType_c4_button_2, 0)
DEFINE_BASIC_TOKEN(C4_BUTTON_3_196, tokType_c4_button_3, 0)
DEFINE_BASIC_TOKEN(C4_BUTTON_4_196, tokType_c4_button_4, 0)
DEFINE_BASIC_TOKEN(C4_BUTTON_5_196, tokType_c4_button_5, 0)
DEFINE_BASIC_TOKEN(C4_BUTTON_6_196, tokType_c4_button_6, 0)
DEFINE_BASIC_TOKEN(C4_BUTTON_7_196, tokType_c4_button_7, 0)
DEFINE_BASIC_TOKEN(C4_BUTTON_8_196, tokType_c4_button_8, 0)
DEFINE_BASIC_TOKEN(C4_LED_1_STATE_196, tokType_c4_led_1_state, 0)
DEFINE_BASIC_TOKEN(C4_LED_2_STATE_196, tokType_c4_led_2_state, 0)
DEFINE_BASIC_TOKEN(C4_LED_3_STATE_196, tokType_c4_led_3_state, 0)
DEFINE_BASIC_TOKEN(C4_LED_4_STATE_196, tokType_c4_led_4_state, 0)
DEFINE_BASIC_TOKEN(C4_LED_5_STATE_196, tokType_c4_led_5_state, 0)
DEFINE_BASIC_TOKEN(C4_LED_6_STATE_196, tokType_c4_led_6_state, 0)
DEFINE_BASIC_TOKEN(C4_LED_7_STATE_196, tokType_c4_led_7_state, 0)
DEFINE_BASIC_TOKEN(C4_LED_8_STATE_196, tokType_c4_led_8_state, 0)
DEFINE_BASIC_TOKEN(C4_LED_DIM_UP_RATE_196, tokType_c4_led_dim_up_rate, 10)
DEFINE_BASIC_TOKEN(C4_LED_DIM_DOWN_RATE_196, tokType_c4_led_dim_down_rate, 10)
DEFINE_BASIC_TOKEN(C4_LED_DIM_MIN_196, tokType_c4_led_dim_min, 2)
DEFINE_BASIC_TOKEN(C4_LED_DIM_MAX_196, tokType_c4_led_dim_max, 100)
DEFINE_BASIC_TOKEN(C4_LED_ON_TIME_196, tokType_c4_led_on_time, 20)
#endif // DEFINETOKENS


// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint) do {\
  uint8_t ptr[4]; \
  uint8_t curNetwork = emberGetCurrentNetwork(); \
  uint8_t epNetwork; \
  epNetwork = emberAfNetworkIndexFromEndpoint(1); \
  if((endpoint) == 1 || ((endpoint) == EMBER_BROADCAST_ENDPOINT && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_on_off *)ptr, TOKEN_ON_OFF_1); \
    emberAfWriteServerAttribute(1, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE); \
  } \
  epNetwork = emberAfNetworkIndexFromEndpoint(2); \
  if((endpoint) == 2 || ((endpoint) == EMBER_BROADCAST_ENDPOINT && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_on_off *)ptr, TOKEN_ON_OFF_2); \
    emberAfWriteServerAttribute(2, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE); \
  } \
  epNetwork = emberAfNetworkIndexFromEndpoint(3); \
  if((endpoint) == 3 || ((endpoint) == EMBER_BROADCAST_ENDPOINT && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_on_off *)ptr, TOKEN_ON_OFF_3); \
    emberAfWriteServerAttribute(3, ZCL_ON_OFF_CLUSTER_ID, ZCL_ON_OFF_ATTRIBUTE_ID, (uint8_t*)ptr, ZCL_BOOLEAN_ATTRIBUTE_TYPE); \
  } \
  epNetwork = emberAfNetworkIndexFromEndpoint(196); \
  if((endpoint) == 196 || ((endpoint) == EMBER_BROADCAST_ENDPOINT && epNetwork == curNetwork)) { \
    halCommonGetToken((tokType_boot_count *)ptr, TOKEN_BOOT_COUNT_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_BOOT_COUNT_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT32U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_1 *)ptr, TOKEN_C4_LED_1_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_2 *)ptr, TOKEN_C4_LED_2_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_3 *)ptr, TOKEN_C4_LED_3_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_4 *)ptr, TOKEN_C4_LED_4_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_5 *)ptr, TOKEN_C4_LED_5_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_6 *)ptr, TOKEN_C4_LED_6_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_7 *)ptr, TOKEN_C4_LED_7_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_7_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_8 *)ptr, TOKEN_C4_LED_8_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_8_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_button_1 *)ptr, TOKEN_C4_BUTTON_1_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_BUTTON_1_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_button_2 *)ptr, TOKEN_C4_BUTTON_2_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_BUTTON_2_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_button_3 *)ptr, TOKEN_C4_BUTTON_3_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_BUTTON_3_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_button_4 *)ptr, TOKEN_C4_BUTTON_4_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_BUTTON_4_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_button_5 *)ptr, TOKEN_C4_BUTTON_5_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_BUTTON_5_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_button_6 *)ptr, TOKEN_C4_BUTTON_6_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_BUTTON_6_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_button_7 *)ptr, TOKEN_C4_BUTTON_7_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_BUTTON_7_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_button_8 *)ptr, TOKEN_C4_BUTTON_8_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_BUTTON_8_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_1_state *)ptr, TOKEN_C4_LED_1_STATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_1_STATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_2_state *)ptr, TOKEN_C4_LED_2_STATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_2_STATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_3_state *)ptr, TOKEN_C4_LED_3_STATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_3_STATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_4_state *)ptr, TOKEN_C4_LED_4_STATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_4_STATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_5_state *)ptr, TOKEN_C4_LED_5_STATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_5_STATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_6_state *)ptr, TOKEN_C4_LED_6_STATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_6_STATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_7_state *)ptr, TOKEN_C4_LED_7_STATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_7_STATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_8_state *)ptr, TOKEN_C4_LED_8_STATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_8_STATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_dim_up_rate *)ptr, TOKEN_C4_LED_DIM_UP_RATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_DIM_UP_RATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_dim_down_rate *)ptr, TOKEN_C4_LED_DIM_DOWN_RATE_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_DIM_DOWN_RATE_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_dim_min *)ptr, TOKEN_C4_LED_DIM_MIN_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_DIM_MIN_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_dim_max *)ptr, TOKEN_C4_LED_DIM_MAX_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_DIM_MAX_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
    halCommonGetToken((tokType_c4_led_on_time *)ptr, TOKEN_C4_LED_ON_TIME_196); \
    emberAfWriteManufacturerSpecificServerAttribute(196, ZCL_CUSTOM_END_DEVICE_CONFIGURATION_CLUSTER_ID, ZCL_C4_LED_ON_TIME_ATTRIBUTE_ID, 0x1002, (uint8_t*)ptr, ZCL_INT8U_ATTRIBUTE_TYPE); \
  } \
} while(false)


// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER do {\
  uint8_t allZeroData[4]; \
  MEMSET(allZeroData, 0, 4); \
  if ( data == NULL ) data = allZeroData; \
  if ( endpoint == 1 ) { \
    if ( clusterId == 0x06 ) { \
      if ( metadata->attributeId == 0x0000 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_ON_OFF_1, data); \
    } \
  } else if ( endpoint == 2) { \
    if ( clusterId == 0x06 ) { \
      if ( metadata->attributeId == 0x0000 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_ON_OFF_2, data); \
    } \
  } else if ( endpoint == 3) { \
    if ( clusterId == 0x06 ) { \
      if ( metadata->attributeId == 0x0000 && 0x0000 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_ON_OFF_3, data); \
    } \
  } else if ( endpoint == 196) { \
    if ( clusterId == 0xFD01 ) { \
      if ( metadata->attributeId == 0x000D && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_BOOT_COUNT_196, data); \
      if ( metadata->attributeId == 0x0016 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_1_196, data); \
      if ( metadata->attributeId == 0x0017 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_2_196, data); \
      if ( metadata->attributeId == 0x0018 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_3_196, data); \
      if ( metadata->attributeId == 0x0019 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_4_196, data); \
      if ( metadata->attributeId == 0x001A && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_5_196, data); \
      if ( metadata->attributeId == 0x001B && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_6_196, data); \
      if ( metadata->attributeId == 0x001C && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_7_196, data); \
      if ( metadata->attributeId == 0x001D && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_8_196, data); \
      if ( metadata->attributeId == 0x001E && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_BUTTON_1_196, data); \
      if ( metadata->attributeId == 0x001F && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_BUTTON_2_196, data); \
      if ( metadata->attributeId == 0x0020 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_BUTTON_3_196, data); \
      if ( metadata->attributeId == 0x0021 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_BUTTON_4_196, data); \
      if ( metadata->attributeId == 0x0022 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_BUTTON_5_196, data); \
      if ( metadata->attributeId == 0x0023 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_BUTTON_6_196, data); \
      if ( metadata->attributeId == 0x0024 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_BUTTON_7_196, data); \
      if ( metadata->attributeId == 0x0025 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_BUTTON_8_196, data); \
      if ( metadata->attributeId == 0x0026 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_1_STATE_196, data); \
      if ( metadata->attributeId == 0x0027 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_2_STATE_196, data); \
      if ( metadata->attributeId == 0x0028 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_3_STATE_196, data); \
      if ( metadata->attributeId == 0x0029 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_4_STATE_196, data); \
      if ( metadata->attributeId == 0x002A && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_5_STATE_196, data); \
      if ( metadata->attributeId == 0x002B && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_6_STATE_196, data); \
      if ( metadata->attributeId == 0x002C && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_7_STATE_196, data); \
      if ( metadata->attributeId == 0x002D && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_8_STATE_196, data); \
      if ( metadata->attributeId == 0x002E && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_DIM_UP_RATE_196, data); \
      if ( metadata->attributeId == 0x002F && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_DIM_DOWN_RATE_196, data); \
      if ( metadata->attributeId == 0x0030 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_DIM_MIN_196, data); \
      if ( metadata->attributeId == 0x0031 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_DIM_MAX_196, data); \
      if ( metadata->attributeId == 0x0032 && 0x1002 == emberAfGetMfgCode(metadata) &&!emberAfAttributeIsClient(metadata) ) \
        halCommonSetToken(TOKEN_C4_LED_ON_TIME_196, data); \
    } \
  } \
} while(false)


