// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __AF_GEN_EVENT__
#define __AF_GEN_EVENT__


// Code used to configure the cluster event mechanism
#define EMBER_AF_GENERATED_EVENT_CODE \
  EmberEventControl emberAfIdentifyClusterServerTickCallbackControl1; \
  EmberEventControl emberAfOtaBootloadClusterClientTickCallbackControl1; \
  extern EmberEventControl Button_3_Counter_Control; \
  extern EmberEventControl app3B1RAnnouncementEventControl; \
  extern EmberEventControl appBroadcastSearchTypeCT3B1REventControl; \
  extern EmberEventControl appRepeat_NetworkSteeringEventControl; \
  extern EmberEventControl app_Button_1_StatusUpdateEventControl; \
  extern EmberEventControl app_Button_2_StatusUpdateEventControl; \
  extern EmberEventControl app_Button_3_StatusUpdateEventControl; \
  extern EmberEventControl app_Button_Rotatory_StatusUpdateEventControl; \
  extern EmberEventControl app_Button_Rotatory_UpdateEventControl; \
  extern EmberEventControl commissioningLedEventControl; \
  extern EmberEventControl emberAfPluginInterpanFragmentReceiveEventControl; \
  extern EmberEventControl emberAfPluginInterpanFragmentTransmitEventControl; \
  extern EmberEventControl emberAfPluginNetworkSteeringFinishSteeringEventControl; \
  extern EmberEventControl emberAfPluginOtaStorageSimpleEepromPageEraseEventControl; \
  extern EmberEventControl emberAfPluginReportingTickEventControl; \
  extern EmberEventControl emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventControl; \
  extern EmberEventControl findingAndBindingEventControl; \
  extern void Button_3_Counter_Handler(void); \
  extern void app3B1RAnnouncementEventHandler(void); \
  extern void appBroadcastSearchTypeCT3B1REventHandler(void); \
  extern void appRepeat_NetworkSteeringEventHandler(void); \
  extern void app_Button_1_StatusUpdateEventHandler(void); \
  extern void app_Button_2_StatusUpdateEventHandler(void); \
  extern void app_Button_3_StatusUpdateEventHandler(void); \
  extern void app_Button_Rotatory_StatusUpdateEventHandler(void); \
  extern void app_Button_Rotatory_UpdateEventHandler(void); \
  extern void commissioningLedEventHandler(void); \
  extern void emberAfPluginInterpanFragmentReceiveEventHandler(void); \
  extern void emberAfPluginInterpanFragmentTransmitEventHandler(void); \
  extern void emberAfPluginNetworkSteeringFinishSteeringEventHandler(void); \
  extern void emberAfPluginOtaStorageSimpleEepromPageEraseEventHandler(void); \
  extern void emberAfPluginReportingTickEventHandler(void); \
  extern void emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventHandler(void); \
  extern void findingAndBindingEventHandler(void); \
  static void networkEventWrapper(EmberEventControl *control, EmberAfNetworkEventHandler handler, uint8_t networkIndex) \
  { \
    emberAfPushNetworkIndex(networkIndex); \
    emberEventControlSetInactive(*control); \
    (*handler)(); \
    emberAfPopNetworkIndex(); \
  } \
  EmberEventControl emberAfPluginScanDispatchScanNetworkEventControls[1]; \
  extern void emberAfPluginScanDispatchScanNetworkEventHandler(void); \
  void emberAfPluginScanDispatchScanNetworkEventWrapper0(void) { networkEventWrapper(&emberAfPluginScanDispatchScanNetworkEventControls[0], emberAfPluginScanDispatchScanNetworkEventHandler, 0); } \
  static void clusterTickWrapper(EmberEventControl *control, EmberAfTickFunction callback, uint8_t endpoint) \
  { \
    emberAfPushEndpointNetworkIndex(endpoint); \
    emberEventControlSetInactive(*control); \
    (*callback)(endpoint); \
    emberAfPopNetworkIndex(); \
  } \
  void emberAfIdentifyClusterServerTickCallbackWrapperFunction1(void) { clusterTickWrapper(&emberAfIdentifyClusterServerTickCallbackControl1, emberAfIdentifyClusterServerTickCallback, 1); } \
  void emberAfOtaBootloadClusterClientTickCallbackWrapperFunction1(void) { clusterTickWrapper(&emberAfOtaBootloadClusterClientTickCallbackControl1, emberAfOtaBootloadClusterClientTickCallback, 1); } \
  EmberEventControl emberAfPluginZllIdentifyServerTriggerEffectEndpointEventControls[2]; \
  extern void emberAfPluginZllIdentifyServerTriggerEffectEndpointEventHandler(uint8_t endpoint); \
  void emberAfPluginZllIdentifyServerTriggerEffectEndpointEventWrapper1(void) { clusterTickWrapper(&emberAfPluginZllIdentifyServerTriggerEffectEndpointEventControls[0], emberAfPluginZllIdentifyServerTriggerEffectEndpointEventHandler, 1); } \
  void emberAfPluginZllIdentifyServerTriggerEffectEndpointEventWrapper196(void) { clusterTickWrapper(&emberAfPluginZllIdentifyServerTriggerEffectEndpointEventControls[1], emberAfPluginZllIdentifyServerTriggerEffectEndpointEventHandler, 196); } \


// EmberEventData structs used to populate the EmberEventData table
#define EMBER_AF_GENERATED_EVENTS   \
  { &emberAfIdentifyClusterServerTickCallbackControl1, emberAfIdentifyClusterServerTickCallbackWrapperFunction1 }, \
  { &emberAfOtaBootloadClusterClientTickCallbackControl1, emberAfOtaBootloadClusterClientTickCallbackWrapperFunction1 }, \
  { &Button_3_Counter_Control, Button_3_Counter_Handler }, \
  { &app3B1RAnnouncementEventControl, app3B1RAnnouncementEventHandler }, \
  { &appBroadcastSearchTypeCT3B1REventControl, appBroadcastSearchTypeCT3B1REventHandler }, \
  { &appRepeat_NetworkSteeringEventControl, appRepeat_NetworkSteeringEventHandler }, \
  { &app_Button_1_StatusUpdateEventControl, app_Button_1_StatusUpdateEventHandler }, \
  { &app_Button_2_StatusUpdateEventControl, app_Button_2_StatusUpdateEventHandler }, \
  { &app_Button_3_StatusUpdateEventControl, app_Button_3_StatusUpdateEventHandler }, \
  { &app_Button_Rotatory_StatusUpdateEventControl, app_Button_Rotatory_StatusUpdateEventHandler }, \
  { &app_Button_Rotatory_UpdateEventControl, app_Button_Rotatory_UpdateEventHandler }, \
  { &commissioningLedEventControl, commissioningLedEventHandler }, \
  { &emberAfPluginInterpanFragmentReceiveEventControl, emberAfPluginInterpanFragmentReceiveEventHandler }, \
  { &emberAfPluginInterpanFragmentTransmitEventControl, emberAfPluginInterpanFragmentTransmitEventHandler }, \
  { &emberAfPluginNetworkSteeringFinishSteeringEventControl, emberAfPluginNetworkSteeringFinishSteeringEventHandler }, \
  { &emberAfPluginOtaStorageSimpleEepromPageEraseEventControl, emberAfPluginOtaStorageSimpleEepromPageEraseEventHandler }, \
  { &emberAfPluginReportingTickEventControl, emberAfPluginReportingTickEventHandler }, \
  { &emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventControl, emberAfPluginUpdateTcLinkKeyBeginTcLinkKeyUpdateEventHandler }, \
  { &findingAndBindingEventControl, findingAndBindingEventHandler }, \
  { &emberAfPluginScanDispatchScanNetworkEventControls[0], emberAfPluginScanDispatchScanNetworkEventWrapper0 }, \
  { &emberAfPluginZllIdentifyServerTriggerEffectEndpointEventControls[0], emberAfPluginZllIdentifyServerTriggerEffectEndpointEventWrapper1 }, \
  { &emberAfPluginZllIdentifyServerTriggerEffectEndpointEventControls[1], emberAfPluginZllIdentifyServerTriggerEffectEndpointEventWrapper196 }, \


#define EMBER_AF_GENERATED_EVENT_STRINGS   \
  "Identify Cluster Server EP 1",  \
  "Over the Air Bootloading Cluster Client EP 1",  \
  "Button_3_ counter_ control",  \
  "App3 b1 r announcement event control",  \
  "App broadcast search type c t3 b1 r event control",  \
  "App repeat_ network steering event control",  \
  "App_ button_1_ status update event control",  \
  "App_ button_2_ status update event control",  \
  "App_ button_3_ status update event control",  \
  "App_ button_ rotatory_ status update event control",  \
  "App_ button_ rotatory_ update event control",  \
  "Commissioning led event control",  \
  "Interpan Plugin FragmentReceive",  \
  "Interpan Plugin FragmentTransmit",  \
  "Network Steering Plugin FinishSteering",  \
  "OTA Simple Storage EEPROM Driver Plugin PageErase",  \
  "Reporting Plugin Tick",  \
  "Update TC Link Key Plugin BeginTcLinkKeyUpdate",  \
  "Finding and binding event control",  \
  "Scan Dispatch Plugin Scan NWK 0", \
  "ZLL Identify Server Plugin TriggerEffect EP 1", \
  "ZLL Identify Server Plugin TriggerEffect EP 196", \


// The length of the event context table used to track and retrieve cluster events
#define EMBER_AF_EVENT_CONTEXT_LENGTH 2

// EmberAfEventContext structs used to populate the EmberAfEventContext table
#define EMBER_AF_GENERATED_EVENT_CONTEXT { 0x1, 0x3, false, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfIdentifyClusterServerTickCallbackControl1}, \
{ 0x1, 0x19, true, EMBER_AF_LONG_POLL, EMBER_AF_OK_TO_SLEEP, &emberAfOtaBootloadClusterClientTickCallbackControl1}


#endif // __AF_GEN_EVENT__
